clickhouse:
  host: localhost
  port: 9000
remote_storage: gcs
gcs:
  credentials_file: /etc/clickhouse-backup/credentials.json
  bucket: clickhouse
  force_path_style: true
  path: backup
  disable_progress_bar: true
  strategy: ""
  backups_to_keep_local: 0
  backups_to_keep_gcs: 0
  compression_level: 1
  compression_format: gzip
