clickhouse:
  host: localhost
  port: 9000
s3:
  access_key: access-key
  secret_key: it-is-my-super-secret-key
  bucket: clickhouse
  endpoint: http://minio:9000
  acl: private
  force_path_style: true
  path: backup
  disable_ssl: true
  disable_progress_bar: true
  overwrite_strategy: always
backup:
  strategy: archive
  backups_to_keep_local: 1
  backups_to_keep_s3: 2
