name: Go

on:
  push:
    branches:
      - '*'
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        clickhouse:
          - '1.1.54390'
          - '19.4.4.33'
          - '19.15.3.6'
          - '20.1.3.7'
          - '20.6.3.28'
    steps:
      - name: Integration test
        env:
          CLICKHOUSE_VERSION: ${{ matrix.clickhouse }}
        uses: actions/checkout@v2, actions/setup-go@v2
        with:
          go-version: '^1.14'
      - run: make build
      - run: make config
      - run: make test  
      - run: echo "CLICKHOUSE_VERSION=${CLICKHOUSE_VERSION}"

